apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: root-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LorenzoGParisi/argo-cd
    path: root-app/
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: root-app
  syncPolicy:
    automated:
      selfHeal: true