apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcName }}
  namespace: {{ .Values.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.storageClass | quote }}
  volumeMode: Filesystem
